export const AR = {
  nav: {
    client: "عميل",
    clientDesc: "استئجار سيارة",
    agency: "وكالة تأجير",
    agencyDesc: "إدارة أسطولي",
    loginBtn: "تسجيل الدخول",
    vehicles: "سيارات",
    services: "خدمات",
    pricing: "الأسعار",
    about: "معلومات عنا",
    login: "تسجيل الدخول",
    aboutUs: "معلومات عنا",
  },
  registre: {
    successTitle: "تم إنشاء الحساب!",
    successText: "تم إنشاء حسابك بنجاح. جاري التوجيه…",
    userSpace: "مساحة المستخدم",
    title: "إنشاء حسابك",
    subtitle: "انضم إلى UppCar اليوم.",
    googleBtn: "التسجيل باستخدام Google",
    orEmail: "أو باستخدام البريد الإلكتروني",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "البريد الإلكتروني الخاص بك",
    passLabel: "كلمة المرور",
    passPlaceholder: "كلمة المرور",
    confirmLabel: "تأكيد كلمة المرور",
    confirmPlaceholder: "أعد إدخال كلمة المرور",
    passMismatch: "كلمات المرور غير متطابقة",
    loading: "جاري الإنشاء...",
    submitBtn: "إنشاء حسابي",
    hasAccount: "لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول.",
    errorServer: "خطأ في الاتصال بالخادم",
  }
};
