export const LOGIN_AR = {
  eyebrow: "فضاء الوكالة",
  title: "مرحبًا بعودتك !",
  subtitle: "سجّل دخولك إلى فضاء وكالتك لإدارة نشاطك.",
  emailLabel: "البريد الإلكتروني المهني",
  emailPlaceholder: "agence@example.com",
  passwordLabel: "كلمة المرور",
  remember: "تذكّرني",
  forgot: "نسيت كلمة المرور؟",
  submit: "تسجيل الدخول",
  loading: "جارٍ الاتصال…",
  success: "✅ متصل — جارٍ إعادة التوجيه…",
  divider: "أو الاستمرار بـ",
  noAccount: "ليس لديك حساب؟",
  register: "إنشاء حساب وكالة",
  errorFill: "يرجى ملء جميع الحقول.",
  errorLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  leftTag1: "أدِر وكالتك",
  leftTag2: "لتأجير السيارات",
  leftTag3: "بذكاء.",
  leftSub: "انضم إلى أكثر من 1,200 وكالة تثق في UppCar لإدارة أسطولها وحجوزاتها وتحليلاتها في الوقت الفعلي.",
  pills: ["لوحة تحكم مباشرة", "تتبع GPS للأسطول", "تحليلات متقدمة", "بدون التزام"],
  decoLabel1: "إيرادات الشهر",
  decoSub1: "↑ +24% مقارنة بمارس",
  decoLabel2: "الأسطول النشط",
  decoVehicles: "مركبة",
  decoSub2: "3 في الإيجار · 9 متاحة",
  decoLabel3: "الحجوزات",
  decoMonth: "شهر",
};