export const LOGIN_FR = {
  eyebrow: "Espace Agence",
  title: "Bon retour !",
  subtitle: "Connectez-vous à votre espace agence pour gérer votre activité.",
  emailLabel: "Email professionnel",
  emailPlaceholder: "agence@example.com",
  passwordLabel: "Mot de passe",
  remember: "Se souvenir de moi",
  forgot: "Mot de passe oublié ?",
  submit: "Se connecter",
  loading: "Connexion…",
  success: "✅ Connecté — redirection…",
  divider: "ou continuer avec",
  noAccount: "Pas encore de compte ?",
  register: "Créer un compte agence",
  errorFill: "Veuillez remplir tous les champs.",
  errorLogin: "Email ou mot de passe incorrect.",
  leftTag1: "Gérez votre",
  leftTag2: "agence de location",
  leftTag3: "intelligemment.",
  leftSub: "Rejoignez +1 200 agences qui font confiance à UppCar pour piloter leur flotte, réservations et analytics en temps réel.",
  pills: ["Tableau de bord live", "GPS & suivi flotte", "Analytics avancés", "Sans engagement"],
  decoLabel1: "Revenu ce mois",
  decoSub1: "↑ +24% vs mars",
  decoLabel2: "Flotte active",
  decoVehicles: "véhicules",
  decoSub2: "3 en location · 9 dispo",
  decoLabel3: "Réservations",
  decoMonth: "mois",
};