export const AR = {
  nav: {
    client: "عميل",
    clientDesc: "استئجار سيارة",
    agency: "وكالة تأجير",
    agencyDesc: "إدارة أسطولي",
    loginBtn: "تسجيل الدخول",
    vehicles: "سيارات",
    services: "خدمات",
    pricing: "الأسعار",
    registre: "إنشاء حساب",
    aboutUs: "معلومات عنا",
  },
  login: {
    successTitle: "مرحباً بك!",
    successText: "تم تسجيل الدخول بنجاح. جاري التوجيه…",
    userSpace: "مساحة المستخدم",
    title: "مرحباً بعودتك!",
    subtitle: "قم بتسجيل الدخول إلى حسابك للمتابعة.",
    googleBtn: "المتابعة باستخدام Google",
    orEmail: "أو باستخدام البريد الإلكتروني",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "البريد الإلكتروني الخاص بك",
    passLabel: "كلمة المرور",
    passPlaceholder: "كلمة المرور",
    forgotPass: "هل نسيت كلمة المرور؟",
    loading: "جاري تسجيل الدخول...",
    submitBtn: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    createAccount: "إنشاء حساب.",
    errorServer: "خطأ في الاتصال بالخادم",
    errorCreds: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    agencySpace: "مساحة الوكالة الاحترافية",
    pilot: "قُد.",
    analyze: "حلل.",
    dominate: "سيطر.",
    saasDesc: "منصة SaaS مصممة للوكالات الحديثة.",
    activeAgencies: "وكالات نشطة",
    uptime: "وقت تشغيل مضمون",
    avgRevenue: "متوسط الدخل",
    bookingSpeed: "سرعة الحجز",
    featDashboard: "لوحة تحكم في الوقت الفعلي",
    featFleet: "إدارة أسطول ذكية",
    featAI: "تحليلات وتوقعات الذكاء الاصطناعي",
    featCRM: "إدارة العملاء وبرامج الولاء",
    success: "تم تسجيل الدخول بنجاح",
    welcomeBack: "مرحباً بك في",
    redirecting: "سيتم فتح لوحة التحكم خلال ثوانٍ…",
    agencyAccess: "دخول الوكالة",
    welcome: "مرحباً،",
    connect: "سجل دخولك.",
    secureDashboard: "الوصول إلى لوحة تحكم الوكالة الآمنة.",
    email: "البريد الإلكتروني",
    emailPlaceholder: "agency@exemple.ma",
    password: "كلمة المرور",
    remember: "تذكرني",
    forgot: "هل نسيت كلمة المرور؟",
    btn: "الدخول إلى لوحة التحكم",
    noAccountQ: "ليس لديك حساب بعد؟",
    createAgencyAccount: "إنشاء مساحة للوكالة"
  }
};
