export const FR = {
    nav: {
        client: "Client",
        clientDesc: "Louer un véhicule",
        agency: "Agence",
        agencyDesc: "Gérer ma flotte",
        loginBtn: "Se connecter",
        vehicles: "Véhicules",
        services: "Services",
        pricing: "Tarifs",
        registre: "S'inscrire",
        aboutUs: "À propos",
    },
    login: {
        successTitle: "Bienvenue !",
        successText: "Connexion réussie. Redirection en cours…",
        userSpace: "Espace Utilisateur",
        title: "Heureux de vous revoir !",
        subtitle: "Connectez-vous à votre compte pour continuer.",
        googleBtn: "Continuer avec Google",
        orEmail: "Ou avec votre adresse e-mail",
        emailLabel: "Adresse e-mail",
        emailPlaceholder: "Votre adresse e-mail",
        passLabel: "Mot de passe",
        passPlaceholder: "Votre mot de passe",
        forgotPass: "Mot de passe oublié ?",
        loading: "Connexion en cours...",
        submitBtn: "Se connecter",
        noAccount: "Vous n'avez pas de compte ?",
        createAccount: "Inscrivez-vous.",
        errorServer: "Erreur de connexion au serveur",
        errorCreds: "Adresse e-mail ou mot de passe incorrect",
    }
};
